vich_uploader:
    db_driver: orm

    mappings:
        meme:
            uri_prefix: /images/memes
            upload_destination: '%kernel.project_dir%/public/images/memes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 
        users:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 
    metadata:
        type: attribute   